### ISSUE TITLE
Regular User Login + LinkedIn Login + Google Login + Facebook Login | sprint_5

### ISSUE THREAD

**Issue by BastianHub** [IndyTechFellowship/United-Way-Web#38]
![image](https://cloud.githubusercontent.com/assets/22896320/21254905/a754b6ca-c336-11e6-8c27-17ba0ca1e054.png)

Explore opportunities to login using social media sites. Fb, LinkedIn, and Google.

**Comment by mhoc** [comment]
Facebook and Google are very easy. LinkedIn is probably 4% harder than very easy. Email/password is only difficult because we'd need a username/password field, which affects design but is easy on dev's end (not very easy, just easy). 

1 person should do all of this. I can take charge.

Part 2 of this issue will be setting up patterns to detect if a user is logged in.
